### ISSUE TITLE
Pretrained PointRCNN model failed to predict 3D labels on KITTI dataset

### ISSUE THREAD

**Issue by yahoo55025502** [YurongYou/MODEST#4]
Hi, I download the pretrained pointrcnn model and tested it on KITTI pointcloud data. 
But It didn't predict any 3D labels on the data I tested.
![Screenshot from 2022-07-20 17-49-46](https://user-images.githubusercontent.com/71062061/179953363-92836038-fe6e-46c9-8150-4733ed41ebf5.png)

The command I used to test is as follows ( the current directory is OpenPCDet/tools):
python demo.py --cfg_file cfgs/lyft_models/pointrcnn_dynamic_obj.yaml --ckpt prcnn_round_40.pth --data_path <KITTI_DATA_FOLDER>/training_data/velodyne/003334.bin 

I also tested other models like SECOND or PointPillars, and both are able to predict some 3D labels on the same data. So I think maybe there is some problem with PointRCNN pretrained model?
Thanks!

**Comment by YurongYou** [comment]
Hi yahoo55025502, thanks for your interest! I think the issue is that Lyft's LiDAR has a fake intensity channel (they fill it with 100) while KITTI has a real intensity channel. When applied to KITTI, you can force the intensity to be the same as that in lyft by adding `CONSTANT_REFLEX=100` in the dataset config file (`cfgs/lyft_models/pointrcnn_dynamic_obj.yaml `)

**Comment by yahoo55025502** [comment]
Now the problem is fixed, thanks for your help!
